<?php
/**
 * Catalog Config
 *
 * File    : catalog-config.php
 * Project : Baca Di Teras
 * Version : 1.0.0
 *
 * Data statis untuk halaman katalog buku.
 * Dirancang agar mudah dipindah ke database (tabel: books, categories, publishers).
 */

// ── Opsi Filter ──────────────────────────────────────────────

$categoryList = [
    ['id' => 'fiksi',       'label' => 'Fiksi'],
    ['id' => 'teknologi',   'label' => 'Teknologi'],
    ['id' => 'budaya-lokal','label' => 'Budaya Lokal'],
    ['id' => 'pertanian',   'label' => 'Pertanian'],
    ['id' => 'sastra-anak', 'label' => 'Sastra Anak'],
    ['id' => 'sejarah',     'label' => 'Sejarah'],
    ['id' => 'nonfiksi',    'label' => 'Nonfiksi'],
    ['id' => 'kuliner',     'label' => 'Kuliner'],
];

$publisherList = [
    ['id' => 'gramedia',       'label' => 'Gramedia'],
    ['id' => 'bentang-pustaka','label' => 'Bentang Pustaka'],
    ['id' => 'mizan',          'label' => 'Mizan'],
    ['id' => 'local-press',    'label' => 'Local Press'],
];

$libraryFilterList = [
    ['id' => '',                     'label' => 'Semua Perpustakaan'],
    ['id' => 'perpustakaan-utama',   'label' => 'Perpustakaan Utama Desa'],
    ['id' => 'taman-baca-komunitas', 'label' => 'Taman Baca Komunitas'],
    ['id' => 'perpustakaan-digital', 'label' => 'Perpustakaan Digital Teras'],
];

$sortOptionList = [
    ['id' => 'terbaru',    'label' => 'Koleksi Terbaru'],
    ['id' => 'terpopuler', 'label' => 'Terpopuler'],
    ['id' => 'a-z',        'label' => 'Judul A–Z'],
    ['id' => 'z-a',        'label' => 'Judul Z–A'],
];

// ── Data Buku ────────────────────────────────────────────────

$catalogBookList = [
    [
        'id'            => 'digital-teras',
        'title'         => 'Digital Teras: Navigating the Web',
        'author'        => 'Dr. Ahmad Santoso',
        'category'      => 'Teknologi',
        'badge'         => 'Baru',
        'image'         => '/custom/assets/images/book-cover-3.png',
        'href'          => '/katalog/digital-teras',
        'penerbit'      => 'Gramedia',
        'perpustakaan'  => 'perpustakaan-digital',
        'ketersediaan'  => 'tersedia',
        'stok'          => 4,
        'antrian'       => 0,
    ],
    [
        'id'            => 'modern-farmers-journal',
        'title'         => "Modern Farmer's Journal 2024",
        'author'        => 'Teras Agrotech Team',
        'category'      => 'Pertanian',
        'badge'         => null,
        'image'         => '/custom/assets/images/book-cover-4.png',
        'href'          => '/katalog/modern-farmers-journal',
        'penerbit'      => 'Local Press',
        'perpustakaan'  => 'taman-baca-komunitas',
        'ketersediaan'  => 'dipinjam',
        'stok'          => 0,
        'antrian'       => 2,
    ],
    [
        'id'            => 'folklore-of-the-valley',
        'title'         => 'Folklore of the Valley',
        'author'        => 'Maria Sastrawan',
        'category'      => 'Budaya Lokal',
        'badge'         => null,
        'image'         => '/custom/assets/images/book-cover-5.png',
        'href'          => '/katalog/folklore-of-the-valley',
        'penerbit'      => 'Bentang Pustaka',
        'perpustakaan'  => 'perpustakaan-utama',
        'ketersediaan'  => 'dipesan',
        'stok'          => 1,
        'antrian'       => 2,
    ],
    [
        'id'            => 'global-finance-villages',
        'title'         => 'Global Finance for Villages',
        'author'        => 'Prof. Hendra Wijaya',
        'category'      => 'Nonfiksi',
        'badge'         => null,
        'image'         => '/custom/assets/images/book-cover-1.png',
        'href'          => '/katalog/global-finance-villages',
        'penerbit'      => 'Gramedia',
        'perpustakaan'  => 'perpustakaan-utama',
        'ketersediaan'  => 'tersedia',
        'stok'          => 1,
        'antrian'       => 0,
    ],
    [
        'id'            => 'history-of-teras-settlement',
        'title'         => 'History of Teras Settlement',
        'author'        => 'Dr. S. Margono',
        'category'      => 'Sejarah',
        'badge'         => null,
        'image'         => '/custom/assets/images/book-cover-2.png',
        'href'          => '/katalog/history-of-teras-settlement',
        'penerbit'      => 'Local Press',
        'perpustakaan'  => 'perpustakaan-utama',
        'ketersediaan'  => 'tersedia',
        'stok'          => 3,
        'antrian'       => 0,
    ],
    [
        'id'            => 'culinary-heritage-teras',
        'title'         => 'Culinary Heritage of Teras',
        'author'        => 'Ibu Siti Rahayu',
        'category'      => 'Kuliner',
        'badge'         => 'Populer',
        'image'         => '/custom/assets/images/book-cover-4.png',
        'href'          => '/katalog/culinary-heritage-teras',
        'penerbit'      => 'Mizan',
        'perpustakaan'  => 'taman-baca-komunitas',
        'ketersediaan'  => 'tersedia',
        'stok'          => 2,
        'antrian'       => 0,
    ],
    [
        'id'            => 'untaian-kisah-lembut',
        'title'         => 'Untaian Kisah Lembut',
        'author'        => 'Rina Sari',
        'category'      => 'Fiksi',
        'badge'         => 'Baru',
        'image'         => '/custom/assets/images/book-cover-1.png',
        'href'          => '/katalog/untaian-kisah-lembut',
        'penerbit'      => 'Bentang Pustaka',
        'perpustakaan'  => 'perpustakaan-utama',
        'ketersediaan'  => 'tersedia',
        'stok'          => 5,
        'antrian'       => 0,
    ],
    [
        'id'            => 'koleksi-puisi-nusantara',
        'title'         => 'Koleksi Puisi Nusantara',
        'author'        => 'Budi Santoso',
        'category'      => 'Sastra Anak',
        'badge'         => 'Populer',
        'image'         => '/custom/assets/images/book-cover-2.png',
        'href'          => '/katalog/koleksi-puisi-nusantara',
        'penerbit'      => 'Mizan',
        'perpustakaan'  => 'taman-baca-komunitas',
        'ketersediaan'  => 'tersedia',
        'stok'          => 3,
        'antrian'       => 0,
    ],
    [
        'id'            => 'pemikiran-tokoh-bangsa',
        'title'         => 'Pemikiran Tokoh Bangsa',
        'author'        => 'Dr. Ahmad Fauzi',
        'category'      => 'Nonfiksi',
        'badge'         => 'Baru',
        'image'         => '/custom/assets/images/book-cover-3.png',
        'href'          => '/katalog/pemikiran-tokoh-bangsa',
        'penerbit'      => 'Gramedia',
        'perpustakaan'  => 'perpustakaan-digital',
        'ketersediaan'  => 'dipinjam',
        'stok'          => 0,
        'antrian'       => 1,
    ],
    [
        'id'            => 'jejak-nusantara',
        'title'         => 'Jejak Nusantara',
        'author'        => 'Siti Rahayu',
        'category'      => 'Sejarah',
        'badge'         => null,
        'image'         => '/custom/assets/images/book-cover-4.png',
        'href'          => '/katalog/jejak-nusantara',
        'penerbit'      => 'Bentang Pustaka',
        'perpustakaan'  => 'perpustakaan-utama',
        'ketersediaan'  => 'tersedia',
        'stok'          => 2,
        'antrian'       => 0,
    ],
    [
        'id'            => 'dongeng-desa-teras',
        'title'         => 'Dongeng Desa Teras',
        'author'        => 'Tim Literasi Teras',
        'category'      => 'Sastra Anak',
        'badge'         => 'Baru',
        'image'         => '/custom/assets/images/book-cover-5.png',
        'href'          => '/katalog/dongeng-desa-teras',
        'penerbit'      => 'Local Press',
        'perpustakaan'  => 'taman-baca-komunitas',
        'ketersediaan'  => 'tersedia',
        'stok'          => 6,
        'antrian'       => 0,
    ],
    [
        'id'            => 'teknologi-pertanian-santara',
        'title'         => 'Teknologi Pertanian Nusantara',
        'author'        => 'Ir. Bambang Setiawan',
        'category'      => 'Pertanian',
        'badge'         => null,
        'image'         => '/custom/assets/images/book-cover-2.png',
        'href'          => '/katalog/teknologi-pertanian-nusantara',
        'penerbit'      => 'Gramedia',
        'perpustakaan'  => 'perpustakaan-digital',
        'ketersediaan'  => 'tersedia',
        'stok'          => 2,
        'antrian'       => 0,
    ],
];
